service: backend

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1
  stage: dev

plugins:
   - serverless-appsync-plugin

custom:
  appSync:
    name: youtubeAppSyncApi
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      awsRegion: us-west-1
      defaultAction: ALLOW
      userPoolId: !Ref cognitoUserPool
    mappingTemplatesLocation: mapping-templates
    mappingTemplates: 
      - type: Query 
        field: getBookById
        dataSource: booksTable
      - type: Mutation 
        field: createBook
        dataSource: booksTable
    dataSources:
      - type: AMAZON_DYNAMODB
        name: booksTable
        config: 
          tableName: !Ref booksTable

resources:
 Resources:
  ${file(resources.yml)}
